### ISSUE TITLE
an illegal memory access was encountered

### ISSUE THREAD

**Issue by sshan-zhao** [ClementPinard/Pytorch-Correlation-extension#3]
Hi, when I use your code in pytorch 0.4.1, cuda 9.0, an error occurs:
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1532571933727/work/aten/src/THC/THCCachingHostAllocator.cpp line=271 error=77 : an illegal memory access was encountered
if I do not use the correlation layer, that would be ok.
Do you have any idea? Thank you!

**Comment by ClementPinard** [comment]
Yes, there has been some problems with last version (0.0.7), because there was a typo, which made this error occur when H and W where not the same (I did not ran tests thoroughly enough, I'm so sorry! :confused: )

I uploaded a new version (0.0.8) this morning, and it should be solved, so you should try to upgrade your correlation sampler.

**Comment by sshan-zhao** [comment]
Hi Clement,
Thank you so much for your reply!
Actually, I indeed used the updated version. And I tested the version 0.0.8
again, however, the error still occurs. And it is weird that the error
occurs randomly, sometimes it occurs after several hundreds of iterations,
but sometimes just several iterations. I checked your code, and it seems
like that there is no bug. In fact, I wanna use your code in PWC-Net()
https://github.com/NVlabs/PWC-Net/tree/master/PyTorch, because the provided
correlation layer is based on pytorch 0.2, while my project is based on
0.4. I really have no idea about it. Anyway, thank you and thank you for
releasing this code.

Best regards,
Shanshan

Clément Pinard <notifications@github.com> 于2018年8月23日周四 下午10:04写道：

**Comment by ClementPinard** [comment]
That's weird, the `view` operation is supposed to handle this automatically, see [here](https://github.com/ClementPinard/FlowNetPytorch/blob/master/models/util.py#L39) how I did it for my implementation of flownetc.

Anyway I'm glad it could work for you in the end !
